{-
   This file is automatically generated by elm-graphql. Do not modify!
-}


module GraphQL.Ahead exposing (queryLinks, QueryLinksResult)

import Task exposing (Task)
import Json.Decode exposing (..)
import Json.Encode exposing (encode)
import Http
import GraphQL exposing (apply, ID)


endpointUrl : String
endpointUrl =
    "http://localhost:4000/graphql"


type alias QueryLinksResult =
    { store :
        { linkConnection :
            { edges :
                List
                    { node :
                        { id : Maybe String
                        , title : Maybe String
                        , url : Maybe String
                        , createdAt : Maybe String
                        }
                    }
            }
        }
    }


queryLinks : { queryParam : String } -> Task Http.Error QueryLinksResult
queryLinks params =
    let
        graphQLQuery =
            """query queryLinks($queryParam: String!) { store { linkConnection(query: $queryParam) { edges { node { id title url createdAt } } } } }"""
    in
        let
            graphQLParams =
                Json.Encode.object
                    [ ( "queryParam", Json.Encode.string params.queryParam )
                    ]
        in
            GraphQL.query endpointUrl graphQLQuery "queryLinks" (encode 0 graphQLParams) queryLinksResult


queryLinksResult : Decoder QueryLinksResult
queryLinksResult =
    map QueryLinksResult
        ("store"
            := (map (\linkConnection -> { linkConnection = linkConnection })
                    ("linkConnection"
                        := (map (\edges -> { edges = edges })
                                ("edges"
                                    := (list
                                            (map (\node -> { node = node })
                                                ("node"
                                                    := (map (\id title url createdAt -> { id = id, title = title, url = url, createdAt = createdAt }) (maybe ("id" := string))
                                                            `apply` (maybe ("title" := string))
                                                            `apply` (maybe ("url" := string))
                                                            `apply` (maybe ("createdAt" := string))
                                                       )
                                                )
                                            )
                                       )
                                )
                           )
                    )
               )
        )
